name: user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  components: ^0.0.1
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  device_preview_plus: ^2.1.3
  device_preview: ^1.2.0
  choice: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/svg/
    - assets/png/
