name: business_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  components: ^0.0.1
  device_preview: ^1.2.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  date_picker_plus: ^4.1.0
  fl_chart: ^0.69.0
  easy_localization: ^3.0.7
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/svg/
    - assets/png/
    - assets/translations/
